apiVersion: iam.tenxcloud.com/v1alpha1
kind: User
metadata:
  labels:
    t7d.io.username: client2
  name: client2
spec:
  description: client2 用户信息的描述
  email: client2@tenxcloud.com
  groups:
  - observability
  - system:nodes
  - system:masters
  - resource-reader
  - iam.tenxcloud.com
  - observability
  name: client2
  phone: "18890901212"
  role: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: client2:blockchain:common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blockchain:common
subjects:
- kind: User
  name: client2