---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ibp-com-v1beta1-network
  failurePolicy: Fail
  name: network.mutate.webhook
  rules:
  - apiGroups:
    - ibp.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ibp-com-v1beta1-proposal
  failurePolicy: Fail
  name: proposal.mutate.webhook
  rules:
  - apiGroups:
    - ibp.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proposals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ibp-com-v1beta1-vote
  failurePolicy: Fail
  name: vote.mutate.webhook
  rules:
  - apiGroups:
    - ibp.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - votes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ibp-com-v1beta1-network
  failurePolicy: Fail
  name: network.validate.webhook
  rules:
  - apiGroups:
    - ibp.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - networks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ibp-com-v1beta1-proposal
  failurePolicy: Fail
  name: proposal.validate.webhook
  rules:
  - apiGroups:
    - ibp.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - proposals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ibp-com-v1beta1-vote
  failurePolicy: Fail
  name: vote.validate.webhook
  rules:
  - apiGroups:
    - ibp.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - votes
  sideEffects: None
