apiVersion: ibp.com/v1beta1
kind: Network
metadata:
  name: network-sample
spec:
  license:
    accept: true
  federation: federation-sample
  orderSpec:
    secret:
      enrollment:
        tls:
          enrolltoken: <enrolltoken>
        component:
          enrolltoken: <enrolltoken>
    license:
      accept: true
    images:
      grpcwebImage: hyperledgerk8s/grpc-web
      grpcwebTag: latest
      ordererImage: hyperledgerk8s/fabric-orderer
      ordererInitImage: hyperledgerk8s/ubi-minimal
      ordererInitTag: latest
      ordererTag: 2.4.7
  members:
    - name: org1
      namespace: org1
      initiator: true
    - name: org2
      namespace: org2
