apiVersion: ibp.com/v1beta1
kind: Network
metadata:
  name: network-sample3
spec:
  license:
    accept: true
  federation: federation-sample
  initialToken: <enrolltoken>
  orderSpec:
    license:
      accept: true
    ordererType: "etcdraft"
    clusterSize: 3
    ingress:
      class: "portal-ingress"
  members:
    - name: org1
      initiator: true
    - name: org2
