apiVersion: ibp.com/v1beta1
kind: ChaincodeBuild
metadata:
  name: chaincodebuild-sample-minio-upgrade-chaincode
spec:
  license:
    accept: true
  network: network-sample3
  id: go-contract
  version: "0.2"
  initiator: org1
  pipelineRunSpec:
    minio:
      bucket: "bestchains"
      object: "go-contract"
    dockerBuild:
      pushSecret: "dockerhub-secret"
      appImage: hyperledgerk8stest/go-contract-basic:v1
      dockerfile: Dockerfile
      context: bestchains/go-contract/
