name: Sync Upstream

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # Trigger manually

jobs:
  sync:
    if: github.repository == 'bestchains/fabric-operator'
    runs-on: ubuntu-22.04
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: bestchains
          base: main
          head: main
          auto_merge: 'false'
          pr_title: Sync with hyperledger-labs/fabric-operator
          pr_message: If there is a conflict, it is recommended to manually merge the conflicting commits, and then manually execute the sync github action.
